### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pladams9** [Plaban9/ASCIIRogueLike#3]
I forked your repository to use as an exercise<sup>1</sup>, and after I started working on it, realized that it does not have a license. Would you consider adding an open source license to this?

<sup>1</sup>Basically, I'm just improving existing code and possibly extending some, for fun/learning. Your codebase was small and complete, so it fit what I needed perfectly.

**Comment by Plaban9** [comment]
Hello Peter,

This project was made when I just started my journey in Game Development during 2nd year in my college. I followed tutorials from this person<https://www.youtube.com/user/makinggameswithben/videos> on youtube and at the same time tried to implement some newly learnt Design Patterns during that time I learnt in college.

Regarding your question,
 Would you consider adding an open source license to this?
Sure, Why not?
Just tell me the license that suits you the most and I will update it.

Happy Coding!!

P.S.: You might find the code not optimized, inconsistent or buggy since it was just the start of my game development journey and a newbie in Design Patterns.

Regards,
Plaban
________________________________

**Comment by pladams9** [comment]
Thank you, Plaban. I think the MIT license makes sense here.

I definitely understand it not being perfect. Part of the appeal is digging into where I could improve a an existing project. I appreciate you responding - thanks again.

**Comment by Plaban9** [comment]
Hi Peter,

I updated the license to MIT as per your requirement.

Regards,
Plaban
